import {
  Award,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Camera,
  CalendarDays,
  ClipboardCheck,
  Coins,
  Film,
  Gauge,
  Gift,
  HandHeart,
  Home,
  LayoutDashboard,
  Library,
  Megaphone,
  MonitorPlay,
  Package,
  Route,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  Trophy,
  User,
  Users,
} from "lucide-react";
import type {
  Department,
  DepartmentId,
  Employee,
  ExperienceEvent,
  ExcellenceLog,
  JourneyCardArea,
  JourneySkin,
  LeadershipAchievement,
  LeadershipRecognition,
  LeadershipReward,
  CoachingInsight,
  MenuConfiguration,
  NavItem,
  ExperienceAchievement,
  ExperienceDisplaySlide,
  ExperienceSeason,
  LaunchReadinessItem,
  LeadershipPointRule,
  Recognition,
  RecognitionBatch,
  RecognitionCategory,
  RecognitionStandard,
  RecognitionType,
  Redemption,
  Reward,
  Role,
  ScoringMetric,
  StudioModule,
  TvPanelSetting,
} from "./types";
import { productLanguage } from "./product-language";

export const chapter = {
  id: "chapter-one-odyssey",
  name: productLanguage.productName,
  subtitle: productLanguage.platformName,
  chapterNumber: productLanguage.seasonLabel,
  chapterTitle: productLanguage.seasonTitle,
  seasonNumber: productLanguage.seasonLabel,
  seasonTitle: productLanguage.seasonTitle,
  phrase: productLanguage.campaignPhrase,
  visualTagline: productLanguage.campaignPhrase,
  tagline: productLanguage.campaignPhrase,
  location: "Celebration Cinema North",
  communityGoalMiles: 15700,
  themeLabel: "Odyssey / North Stars / IMAX 1570",
  themeNote: "Inspired by IMAX 1570 film",
  imaxReference: "15,700 XP - a nod to IMAX 1570 film.",
  startDate: "2026-07-16",
  endDate: "2026-08-12",
  active: true,
};

export const COMMUNITY_GOAL_MILES = chapter.communityGoalMiles;

const nowSeed = "2026-07-01T09:00:00-04:00";

export const seasons: ExperienceSeason[] = [
  {
    id: chapter.id,
    name: productLanguage.productName,
    subtitle: productLanguage.platformName,
    seasonLabel: productLanguage.seasonLabel,
    seasonTitle: productLanguage.seasonTitle,
    startDate: chapter.startDate,
    endDate: chapter.endDate,
    communityXpGoal: chapter.communityGoalMiles,
    welcomeMessage:
      "Welcome to Experience. Recognize the moments that make Celebration Cinema North feel extraordinary.",
    tagline: productLanguage.campaignPhrase,
    heroArtworkUrl: "/brand/celebration-c-frame.png",
    experienceCardArtworkUrl: "/brand/celebration-c-frame.png",
    skinId: "odyssey",
    status: "active",
    active: true,
    previewEnabled: true,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "season-two-draft",
    name: "Experience",
    subtitle: "Future Season Draft",
    seasonLabel: "Season Two",
    seasonTitle: "Untitled",
    startDate: "2026-09-01",
    endDate: "2026-09-30",
    communityXpGoal: 12000,
    welcomeMessage: "Draft the next culture moment without writing code.",
    tagline: "More Than A Movie Starts With Us.",
    heroArtworkUrl: "",
    experienceCardArtworkUrl: "",
    skinId: "standard",
    status: "draft",
    active: false,
    previewEnabled: false,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
];

export const journeySkins: JourneySkin[] = [
  {
    id: "standard",
    name: "Cinema Standard",
    status: "available",
    description:
      "The clean black, white, gray, and Celebration red base system with minimal activation styling.",
    canDisable: false,
    tvTreatment: "Standard recognition loop",
    headline: "Every Mile Matters",
    visualDirection: "Premium cinema UI, sharp contrast, red status accents, no activation texture.",
    motionStyle: "Clean fades and projection sweeps only.",
    texture: "Subtle film grain",
    builderNotes: "Use this when Experience needs to feel reusable outside the Odyssey activation.",
    patternStyle: "film",
    backgroundMode: "clean",
    animationIntensity: 30,
    funLevel: 20,
    doodleDensity: 10,
    marqueeSpeed: 35,
    projectorSweep: 45,
    floatAmplitude: 20,
    confettiLevel: 0,
    titleTreatment: "clean",
    cardTreatment: "flat",
    frameStyle: "standard",
    palette: {
      primary: "#050505",
      secondary: "#ffffff",
      accent: "#d71920",
      foil: "#d71920",
      deep: "#050505",
    },
  },
  {
    id: "odyssey",
    name: "Odyssey / North Stars",
    status: "active",
    description:
      "A premium North Stars skin with storm-dark cinema, recognition leaderboard energy, IMAX 15/70 projection cues, and restrained signal accents.",
    canDisable: true,
    tvTreatment: "Opening signal card, recognition leaderboard, wave floor, projection sweep, 15/70 activation card, and cinematic recognition wall",
    headline: "North Stars",
    visualDirection:
      "Clean cinematic Odyssey without mythology clip art: naval silhouettes, waves, film perforations, premium typography, and Celebration red as the action color.",
    motionStyle: "Slow wave drift, projector sweep, and large type transitions.",
    texture: "Film grain, waterline bands, and 15/70 frame marks",
    builderNotes:
      "Inspired by the provided North Stars reference while staying inside black, white, gray, and Celebration red with only subtle metallic signal accents.",
    patternStyle: "waves",
    backgroundMode: "immersive",
    animationIntensity: 78,
    funLevel: 64,
    doodleDensity: 28,
    marqueeSpeed: 58,
    projectorSweep: 82,
    floatAmplitude: 68,
    confettiLevel: 18,
    titleTreatment: "blockbuster",
    cardTreatment: "poster",
    frameStyle: "filmstrip",
    palette: {
      primary: "#050505",
      secondary: "#d8d8d8",
      accent: "#d71920",
      foil: "#c9a84d",
      deep: "#02080b",
    },
  },
  {
    id: "dune_3",
    name: "Dune 3",
    status: "draft",
    description:
      "Future activation skin slot for desert, spice-route, and premium event theming.",
    canDisable: true,
    tvTreatment: "Draft concept",
    headline: "Dune 3",
    visualDirection: "Draft future skin concept. Disabled until a later activation.",
    motionStyle: "Draft",
    texture: "Draft",
    builderNotes: "Placeholder for future activation development.",
    patternStyle: "doodles",
    backgroundMode: "playful",
    animationIntensity: 55,
    funLevel: 80,
    doodleDensity: 70,
    marqueeSpeed: 72,
    projectorSweep: 40,
    floatAmplitude: 48,
    confettiLevel: 70,
    titleTreatment: "handbill",
    cardTreatment: "ticket",
    frameStyle: "ticket-stub",
    palette: {
      primary: "#050505",
      secondary: "#f4f4f4",
      accent: "#d71920",
      foil: "#c8a46a",
      deep: "#070504",
    },
  },
];

export const activeSkin = journeySkins.find((skin) => skin.status === "active") ?? journeySkins[0];

export const recognitionStandards: RecognitionStandard[] = [
  {
    id: "guest_welcome",
    label: "Every Guest Feels Welcome",
    shortLabel: "Guest Welcome",
    description: "Warm greetings, helpful answers, and confident recoveries.",
  },
  {
    id: "space_exceptional",
    label: "Every Space Looks Exceptional",
    shortLabel: "Presentation",
    description: "Clean, sharp, guest-ready spaces from curb to auditorium.",
  },
  {
    id: "crew_matters",
    label: "Every Crew Member Matters",
    shortLabel: "Teamwork",
    description: "Support across stations, departments, and rush moments.",
  },
  {
    id: "shift_counts",
    label: "Every Shift Counts",
    shortLabel: "Reliability",
    description: "Attendance, punctuality, coverage, and closing strong.",
  },
  {
    id: "detail_matters",
    label: "Every Detail Matters",
    shortLabel: "Details",
    description: "Small choices that protect the premium cinema experience.",
  },
];

export const journeyCardAreas: JourneyCardArea[] = [
  {
    id: "floor_lobby",
    name: "Floor / Lobby",
    description:
      "Guest-facing lobby, auditorium reset, queue flow, wayfinding, and presentation tasks.",
    departmentIds: ["floor"],
    enabled: true,
    sortOrder: 10,
  },
  {
    id: "concessions",
    name: "Concessions",
    description:
      "Line speed, stock readiness, guest handoffs, condiment stations, and rush support.",
    departmentIds: ["concessions"],
    enabled: true,
    sortOrder: 20,
  },
  {
    id: "kitchen_oscars",
    name: "Kitchen / Oscar's",
    description:
      "Food accuracy, kitchen reset, Oscar's presentation, expo communication, and safe handoffs.",
    departmentIds: ["kitchen"],
    enabled: true,
    sortOrder: 30,
  },
  {
    id: "box_guest_services",
    name: "Box Office / Guest Services",
    description:
      "Greeting, queue clarity, guest recovery, membership support, and calm problem solving.",
    departmentIds: ["box_office", "guest_services"],
    enabled: true,
    sortOrder: 40,
  },
  {
    id: "facilities_exterior",
    name: "Facilities / Exterior",
    description:
      "Restroom readiness, exterior walks, utility organization, and building-detail saves.",
    departmentIds: ["facilities"],
    enabled: true,
    sortOrder: 50,
  },
];

export const recognitionTypes: RecognitionType[] = [
  {
    id: "bathroom_excellence",
    chapterId: chapter.id,
    name: "Bathroom Excellence",
    description: "Restrooms are clean, stocked, odor-free, and guest-ready.",
    category: "Excellence Check",
    standardId: "space_exceptional",
    milesValue: 10,
    icon: "BadgeCheck",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 10,
    type: "excellence_check",
  },
  {
    id: "lobby_excellence",
    chapterId: chapter.id,
    name: "Lobby Excellence",
    description: "Lobby presentation is sharp, clear, and welcoming.",
    category: "Excellence Check",
    standardId: "space_exceptional",
    milesValue: 10,
    icon: "Clapperboard",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 20,
    type: "excellence_check",
  },
  {
    id: "theater_excellence",
    chapterId: chapter.id,
    name: "Theater Excellence",
    description: "Auditorium reset meets opening standard between shows.",
    category: "Excellence Check",
    standardId: "space_exceptional",
    milesValue: 10,
    icon: "Film",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 30,
    type: "excellence_check",
  },
  {
    id: "bib_excellence",
    chapterId: chapter.id,
    name: "BIB Excellence",
    description: "BIB area is organized, clean, and ready for rush.",
    category: "Excellence Check",
    standardId: "detail_matters",
    milesValue: 10,
    icon: "Gauge",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 40,
    type: "excellence_check",
  },
  {
    id: "oscars_excellence",
    chapterId: chapter.id,
    name: "Oscar's Excellence",
    description: "Oscar's area is stocked, reset, and premium-presented.",
    category: "Excellence Check",
    standardId: "detail_matters",
    milesValue: 10,
    icon: "Award",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 50,
    type: "excellence_check",
  },
  {
    id: "concession_excellence",
    chapterId: chapter.id,
    name: "Concession Excellence",
    description: "Counters, service line, and backbar are clean and ready.",
    category: "Excellence Check",
    standardId: "detail_matters",
    milesValue: 10,
    icon: "Store",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 60,
    type: "excellence_check",
  },
  {
    id: "utility_excellence",
    chapterId: chapter.id,
    name: "Utility Excellence",
    description: "Utility spaces are organized and service-safe.",
    category: "Excellence Check",
    standardId: "space_exceptional",
    milesValue: 10,
    icon: "ClipboardCheck",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 70,
    type: "excellence_check",
  },
  {
    id: "exterior_excellence",
    chapterId: chapter.id,
    name: "Exterior Excellence",
    description: "Exterior entry points look clean, safe, and welcoming.",
    category: "Excellence Check",
    standardId: "space_exceptional",
    milesValue: 10,
    icon: "Route",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 80,
    type: "excellence_check",
  },
  {
    id: "digital_signage_excellence",
    chapterId: chapter.id,
    name: "Digital Signage Excellence",
    description: "Digital boards and guest-facing signage are accurate.",
    category: "Excellence Check",
    standardId: "detail_matters",
    milesValue: 10,
    icon: "MonitorPlay",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 90,
    type: "excellence_check",
  },
  {
    id: "imax_queue_excellence",
    chapterId: chapter.id,
    name: "IMAX Queue Excellence",
    description: "IMAX 15/70 guest flow feels clear, calm, and premium.",
    category: "Excellence Check",
    standardId: "guest_welcome",
    milesValue: 10,
    icon: "Film",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 100,
    type: "excellence_check",
  },
  {
    id: "parking_lot_exterior_walk",
    chapterId: chapter.id,
    name: "Parking Lot / Exterior Walk",
    description: "Exterior walk-through completed and issues escalated.",
    category: "Excellence Check",
    standardId: "space_exceptional",
    milesValue: 10,
    icon: "Route",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 110,
    type: "excellence_check",
    creditScope: "department",
    journeyCardEligible: false,
  },
  {
    id: "floor_guest_welcome_run",
    chapterId: chapter.id,
    name: "Floor Guest Welcome Run",
    description: "Greeted guests, answered questions, and kept lobby movement clear.",
    category: "Guest Experience",
    standardId: "guest_welcome",
    milesValue: 15,
    icon: "Sparkles",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 130,
    type: "journey_card_task",
    creditScope: "employee",
    journeyCardEligible: true,
    journeyCardAreaIds: ["floor_lobby", "box_guest_services"],
  },
  {
    id: "auditorium_reset_detail",
    chapterId: chapter.id,
    name: "Auditorium Reset Detail",
    description: "Completed a clean auditorium reset that was ready before seating.",
    category: "Details",
    standardId: "space_exceptional",
    milesValue: 15,
    icon: "Film",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 140,
    type: "journey_card_task",
    creditScope: "employee",
    journeyCardEligible: true,
    journeyCardAreaIds: ["floor_lobby", "facilities_exterior"],
  },
  {
    id: "concessions_rush_recovery",
    chapterId: chapter.id,
    name: "Concessions Rush Recovery",
    description: "Helped reset stock, line flow, or guest handoffs during a rush.",
    category: "Teamwork",
    standardId: "crew_matters",
    milesValue: 15,
    icon: "Store",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 150,
    type: "journey_card_task",
    creditScope: "employee",
    journeyCardEligible: true,
    journeyCardAreaIds: ["concessions"],
  },
  {
    id: "kitchen_accuracy_save",
    chapterId: chapter.id,
    name: "Kitchen Accuracy Save",
    description: "Caught an order, timing, or handoff detail before it reached a guest.",
    category: "Details",
    standardId: "detail_matters",
    milesValue: 20,
    icon: "BadgeCheck",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 160,
    type: "journey_card_task",
    creditScope: "employee",
    journeyCardEligible: true,
    journeyCardAreaIds: ["kitchen_oscars"],
  },
  {
    id: "oscars_presentation_reset",
    chapterId: chapter.id,
    name: "Oscar's Presentation Reset",
    description: "Reset Oscar's to a guest-ready, premium presentation standard.",
    category: "Details",
    standardId: "space_exceptional",
    milesValue: 15,
    icon: "Award",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 170,
    type: "journey_card_task",
    creditScope: "employee",
    journeyCardEligible: true,
    journeyCardAreaIds: ["kitchen_oscars"],
  },
  {
    id: "guest_services_recovery_note",
    chapterId: chapter.id,
    name: "Guest Services Recovery Note",
    description: "Documented or resolved a guest issue with calm ownership.",
    category: "Guest Experience",
    standardId: "guest_welcome",
    milesValue: 20,
    icon: "HandHeart",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 180,
    type: "journey_card_task",
    creditScope: "employee",
    journeyCardEligible: true,
    journeyCardAreaIds: ["box_guest_services"],
  },
  {
    id: "facilities_detail_save",
    chapterId: chapter.id,
    name: "Facilities Detail Save",
    description: "Found and fixed a presentation issue before guests noticed it.",
    category: "Details",
    standardId: "detail_matters",
    milesValue: 15,
    icon: "Route",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 190,
    type: "journey_card_task",
    creditScope: "employee",
    journeyCardEligible: true,
    journeyCardAreaIds: ["facilities_exterior"],
  },
  {
    id: "guest_compliment",
    chapterId: chapter.id,
    name: "Guest Compliment",
    description: "A guest specifically complimented the employee's service.",
    category: "Guest Experience",
    standardId: "guest_welcome",
    milesValue: 20,
    icon: "Sparkles",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 200,
    type: "guest_experience",
  },
  {
    id: "survey_mention",
    chapterId: chapter.id,
    name: "Survey Mention",
    description: "Employee was named in a guest survey or written response.",
    category: "Guest Experience",
    standardId: "guest_welcome",
    milesValue: 50,
    icon: "Megaphone",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 210,
    type: "guest_experience",
  },
  {
    id: "guest_recovery",
    chapterId: chapter.id,
    name: "Guest Recovery",
    description: "Employee turned a service issue into a stronger guest moment.",
    category: "Guest Experience",
    standardId: "guest_welcome",
    milesValue: 40,
    icon: "HandHeart",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 220,
    type: "guest_experience",
  },
  {
    id: "help_another_department",
    chapterId: chapter.id,
    name: "Help Another Department",
    description: "Employee stepped across station lines to support the operation.",
    category: "Teamwork",
    standardId: "crew_matters",
    milesValue: 15,
    icon: "Users",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 300,
    type: "teamwork",
  },
  {
    id: "coworker_recognition",
    chapterId: chapter.id,
    name: "Coworker Recognition",
    description: "Crew member was recognized for making another teammate stronger.",
    category: "Teamwork",
    standardId: "crew_matters",
    milesValue: 15,
    icon: "Users",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 310,
    type: "teamwork",
  },
  {
    id: "picked_up_shift",
    chapterId: chapter.id,
    name: "Picked Up Shift",
    description: "Employee picked up coverage when the building needed it.",
    category: "Reliability",
    standardId: "shift_counts",
    milesValue: 40,
    icon: "CalendarDays",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 400,
    type: "reliability",
  },
  {
    id: "stayed_late",
    chapterId: chapter.id,
    name: "Stayed Late",
    description: "Employee stayed late to finish the guest or crew handoff well.",
    category: "Reliability",
    standardId: "shift_counts",
    milesValue: 20,
    icon: "Gauge",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 410,
    type: "reliability",
  },
  {
    id: "perfect_attendance_weekly",
    chapterId: chapter.id,
    name: "Perfect Attendance Weekly",
    description: "Weekly attendance was clean and dependable.",
    category: "Reliability",
    standardId: "shift_counts",
    milesValue: 30,
    icon: "CalendarDays",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 420,
    type: "reliability",
  },
  {
    id: "weekend_warrior",
    chapterId: chapter.id,
    name: "Weekend Warrior",
    description: "Employee showed up strong during weekend volume.",
    category: "Reliability",
    standardId: "shift_counts",
    milesValue: 40,
    icon: "Award",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 430,
    type: "reliability",
  },
  {
    id: "perfect_punctuality_weekly",
    chapterId: chapter.id,
    name: "Perfect Punctuality Weekly",
    description: "Employee clocked in on time and ready for every shift this week.",
    category: "Reliability",
    standardId: "shift_counts",
    milesValue: 20,
    icon: "Gauge",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 440,
    type: "reliability",
  },
  {
    id: "manager_above_beyond",
    chapterId: chapter.id,
    name: "Manager Above & Beyond",
    description: "Manager-awarded recognition for uncommon ownership or detail.",
    category: "Manager Award",
    standardId: "detail_matters",
    milesValue: 50,
    icon: "Award",
    enabled: true,
    requiresManagerVerification: true,
    sortOrder: 500,
    type: "detail",
  },
  {
    id: "projection_detail_save",
    chapterId: chapter.id,
    name: "Projection Detail Save",
    description: "Employee caught a detail before it affected presentation.",
    category: "Details",
    standardId: "detail_matters",
    milesValue: 25,
    icon: "Film",
    enabled: false,
    requiresManagerVerification: true,
    sortOrder: 510,
    type: "detail",
  },
];

export const enabledRecognitionTypes = recognitionTypes
  .filter((type) => type.enabled)
  .sort((a, b) => a.sortOrder - b.sortOrder);

export const excellenceCheckTypes = enabledRecognitionTypes.filter(
  (type) => type.type === "excellence_check",
);

export const recognitionEntryTypes = enabledRecognitionTypes.filter(
  (type) => type.type !== "excellence_check" && type.type !== "journey_card_task",
);

export const departments: Department[] = [
  { id: "guest_services", name: "Guest Services", progressMiles: 2450, goalMiles: 3300 },
  { id: "concessions", name: "Concessions", progressMiles: 2820, goalMiles: 3600 },
  { id: "kitchen", name: "Kitchen / Oscar's", progressMiles: 1390, goalMiles: 2200 },
  { id: "floor", name: "Floor", progressMiles: 3100, goalMiles: 4000 },
  { id: "box_office", name: "Box Office", progressMiles: 1520, goalMiles: 2400 },
  { id: "facilities", name: "Facilities", progressMiles: 1180, goalMiles: 1800 },
];

export const employees: Employee[] = [
  {
    id: "emp-alex",
    name: "Alex Rivera",
    role: "employee",
    department: "floor",
    title: "Floor Crew",
    initials: "AR",
    passportId: "ODY-1570-001",
    passportQrUrl: "http://127.0.0.1:3000/manager/passport/ODY-1570-001",
    journeyCardAreaId: "floor_lobby",
    email: "alex.rivera@north.example",
    accessCode: "AR1570",
    accountStatus: "active",
    miles: 660,
    weeklyMiles: 105,
    reliabilityStreak: 4,
    shift: "Nights",
    lastRecognizedAt: "2026-07-24T18:30:00",
  },
  {
    id: "emp-maya",
    name: "Maya Thompson",
    role: "employee",
    department: "concessions",
    title: "Concessions Crew",
    initials: "MT",
    passportId: "ODY-1570-002",
    passportQrUrl: "http://127.0.0.1:3000/manager/passport/ODY-1570-002",
    journeyCardAreaId: "concessions",
    email: "maya.thompson@north.example",
    accessCode: "MT1570",
    accountStatus: "active",
    miles: 590,
    weeklyMiles: 80,
    reliabilityStreak: 3,
    shift: "Weekends",
    lastRecognizedAt: "2026-07-24T17:10:00",
  },
  {
    id: "emp-eli",
    name: "Eli Brooks",
    role: "employee",
    department: "guest_services",
    title: "Guest Services",
    initials: "EB",
    passportId: "ODY-1570-003",
    passportQrUrl: "http://127.0.0.1:3000/manager/passport/ODY-1570-003",
    journeyCardAreaId: "box_guest_services",
    email: "eli.brooks@north.example",
    accessCode: "EB1570",
    accountStatus: "invited",
    miles: 520,
    weeklyMiles: 65,
    reliabilityStreak: 2,
    shift: "Matinees",
    lastRecognizedAt: "2026-07-24T15:45:00",
  },
  {
    id: "emp-nora",
    name: "Nora Patel",
    role: "employee",
    department: "box_office",
    title: "Box Office",
    initials: "NP",
    passportId: "ODY-1570-004",
    passportQrUrl: "http://127.0.0.1:3000/manager/passport/ODY-1570-004",
    journeyCardAreaId: "box_guest_services",
    email: "nora.patel@north.example",
    accessCode: "NP1570",
    accountStatus: "active",
    miles: 450,
    weeklyMiles: 70,
    reliabilityStreak: 5,
    shift: "Mixed",
    lastRecognizedAt: "2026-07-23T21:00:00",
  },
  {
    id: "emp-dante",
    name: "Dante Williams",
    role: "employee",
    department: "facilities",
    title: "Facilities Crew",
    initials: "DW",
    passportId: "ODY-1570-005",
    passportQrUrl: "http://127.0.0.1:3000/manager/passport/ODY-1570-005",
    journeyCardAreaId: "facilities_exterior",
    email: "dante.williams@north.example",
    accessCode: "DW1570",
    accountStatus: "active",
    miles: 410,
    weeklyMiles: 0,
    reliabilityStreak: 3,
    shift: "Closings",
    lastRecognizedAt: "2026-07-16T19:20:00",
  },
  {
    id: "emp-leah",
    name: "Leah Kim",
    role: "employee",
    department: "kitchen",
    title: "Kitchen / Oscar's Crew",
    initials: "LK",
    passportId: "ODY-1570-006",
    passportQrUrl: "http://127.0.0.1:3000/manager/passport/ODY-1570-006",
    journeyCardAreaId: "kitchen_oscars",
    email: "leah.kim@north.example",
    accessCode: "LK1570",
    accountStatus: "invited",
    miles: 365,
    weeklyMiles: 55,
    reliabilityStreak: 2,
    shift: "Evenings",
    lastRecognizedAt: "2026-07-23T18:05:00",
  },
  {
    id: "mgr-jordan",
    name: "Jordan Ellis",
    role: "manager",
    department: "leadership",
    title: "Shift Manager",
    initials: "JE",
    passportId: "MGR-1570-001",
    passportQrUrl: "http://127.0.0.1:3000/manager/passport/MGR-1570-001",
    journeyCardAreaId: "floor_lobby",
    email: "jordan.ellis@north.example",
    accessCode: "JE1570",
    accountStatus: "active",
    miles: 0,
    weeklyMiles: 0,
    reliabilityStreak: 0,
    shift: "Leadership",
  },
  {
    id: "admin-sam",
    name: "Sam Carter",
    role: "admin",
    department: "leadership",
    title: "General Manager",
    initials: "SC",
    passportId: "GM-1570-001",
    passportQrUrl: "http://127.0.0.1:3000/manager/passport/GM-1570-001",
    journeyCardAreaId: "floor_lobby",
    email: "sam.carter@north.example",
    accessCode: "SC1570",
    accountStatus: "active",
    miles: 0,
    weeklyMiles: 0,
    reliabilityStreak: 0,
    shift: "Leadership",
  },
];

export const recognitionBatches: RecognitionBatch[] = [
  {
    id: "batch-passport-240724",
    employeeId: "emp-alex",
    managerId: "mgr-jordan",
    createdAt: "2026-07-24T18:35:00",
    note: "Experience Card verified after closing rush.",
    source: "passport",
    itemCount: 4,
    totalMiles: 40,
  },
];

export const excellenceLogs: ExcellenceLog[] = [
  {
    id: "check-floor-240724",
    recognitionTypeId: "theater_excellence",
    departmentId: "floor",
    managerId: "mgr-jordan",
    createdAt: "2026-07-24T18:20:00",
    note: "Auditorium reset readiness logged before the evening rush.",
    communityMiles: 10,
  },
  {
    id: "check-concessions-240724",
    recognitionTypeId: "concession_excellence",
    departmentId: "concessions",
    managerId: "mgr-jordan",
    createdAt: "2026-07-24T17:45:00",
    note: "Concession line and backbar were reset and guest-ready.",
    communityMiles: 10,
  },
];

export const recognitions: Recognition[] = [
  {
    id: "rec-1001",
    employeeId: "emp-alex",
    managerId: "mgr-jordan",
    recognitionTypeId: "theater_excellence",
    standardId: "space_exceptional",
    miles: 10,
    note: "Auditorium 7 was reset to opening standard between sold-out shows.",
    createdAt: "2026-07-24T18:30:00",
    batchId: "batch-passport-240724",
    spotlight: true,
  },
  {
    id: "rec-1002",
    employeeId: "emp-maya",
    managerId: "mgr-jordan",
    recognitionTypeId: "guest_compliment",
    standardId: "guest_welcome",
    miles: 20,
    note: "A guest called out the quick refill and warm handoff during rush.",
    createdAt: "2026-07-24T17:10:00",
  },
  {
    id: "rec-1003",
    employeeId: "emp-eli",
    managerId: "mgr-jordan",
    recognitionTypeId: "guest_recovery",
    standardId: "guest_welcome",
    miles: 40,
    note: "Resolved a seating issue calmly and kept the group excited for the show.",
    createdAt: "2026-07-24T15:45:00",
  },
  {
    id: "rec-1004",
    employeeId: "emp-nora",
    managerId: "mgr-jordan",
    recognitionTypeId: "perfect_punctuality_weekly",
    standardId: "shift_counts",
    miles: 20,
    note: "Perfect clock-in timing for the week and clean station starts.",
    createdAt: "2026-07-23T21:00:00",
  },
  {
    id: "rec-1005",
    employeeId: "emp-dante",
    managerId: "mgr-jordan",
    recognitionTypeId: "exterior_excellence",
    standardId: "space_exceptional",
    miles: 10,
    note: "Front entry looked sharp before the evening set.",
    createdAt: "2026-07-16T19:20:00",
  },
  {
    id: "rec-1006",
    employeeId: "emp-alex",
    managerId: "mgr-jordan",
    recognitionTypeId: "help_another_department",
    standardId: "crew_matters",
    miles: 15,
    note: "Jumped to concessions to clear a line before previews started.",
    createdAt: "2026-07-22T20:05:00",
    batchId: "batch-passport-240724",
  },
  {
    id: "rec-1007",
    employeeId: "emp-maya",
    managerId: "mgr-jordan",
    recognitionTypeId: "manager_above_beyond",
    standardId: "detail_matters",
    miles: 50,
    note: "Caught a stock issue early and prevented a service slowdown.",
    createdAt: "2026-07-22T17:35:00",
    spotlight: true,
  },
];

export const leadershipRecognitions: LeadershipRecognition[] = [
  {
    id: "lead-rec-1001",
    leaderId: "mgr-jordan",
    recognizedById: "admin-sam",
    category: "Coaching",
    title: "Calm rush coaching",
    note: "Kept the concessions handoff calm during the evening rush and coached two newer crew members without slowing the line.",
    createdAt: "2026-07-24T21:20:00",
    impact: "Improved crew confidence and protected guest pace.",
  },
  {
    id: "lead-rec-1002",
    leaderId: "mgr-jordan",
    recognizedById: "admin-sam",
    category: "Coverage",
    title: "Recognition coverage follow-through",
    note: "Closed the loop on employees who had not been recognized this week and made the next shift plan clearer.",
    createdAt: "2026-07-23T18:15:00",
    impact: "Reduced recognition gaps before the weekend.",
  },
  {
    id: "lead-rec-1003",
    leaderId: "mgr-jordan",
    recognizedById: "admin-sam",
    category: "Communication",
    title: "Clean manager handoff",
    note: "Left a concise handoff on theater readiness, pending rewards, and Experience Card follow-up.",
    createdAt: "2026-07-22T22:05:00",
    impact: "Helped the next leader start with less guesswork.",
  },
];

export const leadershipAchievements: LeadershipAchievement[] = [
  {
    id: "lead-ach-coverage",
    leaderId: "mgr-jordan",
    title: "Recognition Leader",
    description: "Kept recognition coverage visible across departments for a full week.",
    status: "earned",
    earnedAt: "2026-07-24T21:30:00",
  },
  {
    id: "lead-ach-coach",
    leaderId: "mgr-jordan",
    title: "Culture Champion",
    description: "Logged three leadership recognitions tied to coaching or calm communication.",
    status: "in_progress",
  },
  {
    id: "lead-ach-handoff",
    leaderId: "mgr-jordan",
    title: "Experience Builder",
    description: "Build a consistent manager handoff rhythm for reward, recognition, and presentation work.",
    status: "in_progress",
  },
  {
    id: "lead-ach-presentation",
    leaderId: "mgr-jordan",
    title: "Presentation Leader",
    description: "Verified readiness checks and connected building presentation back to crew recognition.",
    status: "in_progress",
  },
  {
    id: "lead-ach-moment-maker",
    leaderId: "mgr-jordan",
    title: "Moment Maker",
    description: "Captured specific stories that explain why an Experience Moment mattered.",
    status: "earned",
    earnedAt: "2026-07-23T20:30:00",
  },
  {
    id: "lead-ach-focus",
    leaderId: "mgr-jordan",
    title: "Focus Champion",
    description: "Used Today's Focus to guide coaching and recognition during a live shift.",
    status: "in_progress",
  },
  {
    id: "lead-ach-rewards",
    leaderId: "mgr-jordan",
    title: "Rewards Steward",
    description: "Kept reward approvals accurate, timely, and tied to the employee experience.",
    status: "locked",
  },
];

export const leadershipRewards: LeadershipReward[] = [
  {
    id: "lead-reward-development",
    name: "Professional Development Pick",
    description: "Choose a leadership skill focus, course, or book for the next one-on-one with the GM.",
    status: "available",
    fulfillmentNotes: "Scheduled through the GM, not purchased with employee XP.",
  },
  {
    id: "lead-reward-screening",
    name: "Advance Screening Host",
    description: "Host a small crew recognition moment before a manager-approved advance screening.",
    status: "scheduled",
    fulfillmentNotes: "Requires GM approval and staffing coverage.",
  },
  {
    id: "lead-reward-handoff",
    name: "Recognition at Leadership Meeting",
    description: "Public leadership recognition for clean shift communication and follow-through.",
    status: "earned",
    fulfillmentNotes: "Shown in Leadership Achievements instead of employee Rewards.",
  },
  {
    id: "lead-reward-parking",
    name: "Reserved Parking",
    description: "A leadership recognition perk manually approved by the GM.",
    status: "available",
    fulfillmentNotes: "Managers never spend employee XP.",
  },
  {
    id: "lead-reward-lunch",
    name: "Executive Lunch",
    description: "Recognition for leadership habits that improved the team experience.",
    status: "available",
    fulfillmentNotes: "Admin schedules after manual approval.",
  },
  {
    id: "lead-reward-coffee",
    name: "Coffee Gift Card",
    description: "A small leadership thank-you for strong coaching or handoff behavior.",
    status: "available",
    fulfillmentNotes: "Admin approves and fulfills manually.",
  },
];

export const coachingInsights: CoachingInsight[] = [
  {
    id: "coach-coverage-floor",
    leaderId: "mgr-jordan",
    title: "Recognition gap on Facilities",
    detail: "Facilities has fewer recent employee moments than Floor and Concessions.",
    action: "Ask the closing lead what presentation detail deserved recognition tonight.",
    priority: "High",
  },
  {
    id: "coach-reward-queue",
    leaderId: "mgr-jordan",
    title: "Reward queue needs a handoff",
    detail: "Two requests are still awaiting manager review.",
    action: "Approve, fulfill, or leave a clear note before the end-of-shift handoff.",
    priority: "Medium",
  },
  {
    id: "coach-card-entry",
    leaderId: "mgr-jordan",
    title: "Experience Card timing",
    detail: "Batch entry works best when completed before the final manager walk.",
    action: "Collect turned-in cards before the last auditorium reset.",
    priority: "Low",
  },
];

export const leadershipHealth = {
  recognitionCoverage: 83,
  employeesAwaitingRecognition: 1,
  coachingActionsOpen: coachingInsights.filter((insight) => insight.priority !== "Low").length,
  leadershipRecognitionsThisWeek: leadershipRecognitions.length,
};

export const rewards: Reward[] = [
  {
    id: "reward-c-cash-5",
    chapterId: chapter.id,
    name: "$5 C Cash",
    description: "A quick thank-you that can be used like Celebration Cinema cash.",
    milesCost: 125,
    inventoryCount: 24,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Cinema",
    collection: "Everyday Rewards",
    tier: "Tier 1",
    enabled: true,
    sortOrder: 10,
    redemptionLimitPerEmployee: 4,
    fulfillmentNotes: "Manager confirms employee and issues C Cash voucher.",
    featured: true,
    isNew: true,
    almostGoneThreshold: 4,
  },
  {
    id: "reward-c-cash-10",
    chapterId: chapter.id,
    name: "$10 C Cash",
    description: "A flexible reward for employees building steady XP.",
    milesCost: 225,
    inventoryCount: 18,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Cinema",
    collection: "Everyday Rewards",
    tier: "Tier 1",
    enabled: true,
    sortOrder: 20,
    redemptionLimitPerEmployee: 2,
    fulfillmentNotes: "Manager confirms employee and issues C Cash voucher.",
    spotlight: true,
    featured: true,
    almostGoneThreshold: 4,
  },
  {
    id: "reward-movie-ticket",
    chapterId: chapter.id,
    name: "Movie Ticket",
    description: "One movie ticket for a well-earned night out.",
    milesCost: 300,
    inventoryCount: 16,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Cinema",
    collection: "Everyday Rewards",
    tier: "Tier 1",
    enabled: true,
    sortOrder: 30,
    redemptionLimitPerEmployee: 2,
    fulfillmentNotes: "Issue as employee pass voucher.",
    spotlight: true,
    featured: true,
    almostGoneThreshold: 4,
  },
  {
    id: "reward-c-cash-20",
    chapterId: chapter.id,
    name: "$20 C Cash",
    description: "A bigger C Cash win for employees stacking great shifts.",
    milesCost: 425,
    inventoryCount: 10,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Cinema",
    collection: "Everyday Rewards",
    tier: "Tier 2",
    enabled: true,
    sortOrder: 35,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "Manager confirms employee and issues C Cash voucher.",
    featured: true,
    almostGoneThreshold: 3,
  },
  {
    id: "reward-imax-upgrade",
    chapterId: chapter.id,
    name: "IMAX Upgrade",
    description: "Upgrade a movie visit into the big-format Experience.",
    milesCost: 350,
    inventoryCount: 12,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Cinema",
    collection: "Featured Rewards",
    tier: "Tier 1",
    enabled: true,
    sortOrder: 40,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "Confirm showtime availability before fulfillment.",
    seasonExclusive: true,
    isNew: true,
    almostGoneThreshold: 3,
  },
  {
    id: "reward-oscars-voucher",
    chapterId: chapter.id,
    name: "Oscar's Voucher",
    description: "A food reward that feels like part of the movie night.",
    milesCost: 275,
    inventoryCount: 15,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Food",
    collection: "Experience Rewards",
    tier: "Tier 1",
    enabled: true,
    sortOrder: 50,
    redemptionLimitPerEmployee: 2,
    fulfillmentNotes: "Manager hands off voucher and logs fulfillment.",
    almostGoneThreshold: 4,
  },
  {
    id: "reward-gift-card",
    chapterId: chapter.id,
    name: "Gift Card Choice",
    description: "Choose from Amazon, Target, Meijer, or restaurant cards.",
    milesCost: 650,
    inventoryCount: 9,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Gear",
    collection: "Featured Rewards",
    tier: "Tier 2",
    enabled: true,
    sortOrder: 60,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "Confirm vendor choice before approval.",
    featured: true,
    almostGoneThreshold: 3,
  },
  {
    id: "reward-owala",
    chapterId: chapter.id,
    name: "Owala Bottle",
    description: "Crew favorite water bottle for long shifts and break-room bragging.",
    milesCost: 700,
    inventoryCount: 7,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Gear",
    collection: "Featured Rewards",
    tier: "Tier 2",
    enabled: true,
    sortOrder: 70,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "Confirm color choice if inventory allows.",
    featured: true,
    almostGoneThreshold: 3,
  },
  {
    id: "reward-quarter-zip",
    chapterId: chapter.id,
    name: "North Quarter Zip",
    description: "Premium North apparel for employees who keep raising the standard.",
    milesCost: 950,
    inventoryCount: 5,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Gear",
    collection: "Season Exclusives",
    tier: "Tier 2",
    enabled: true,
    sortOrder: 80,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "Confirm size before fulfillment.",
    seasonExclusive: true,
    almostGoneThreshold: 2,
  },
  {
    id: "reward-private-imax",
    chapterId: chapter.id,
    name: "Private IMAX Screening",
    description: "A premium Experience reward for an employee and approved guests.",
    milesCost: 2200,
    inventoryCount: 2,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Experience",
    collection: "Experience Rewards",
    tier: "Tier 3",
    enabled: true,
    sortOrder: 90,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "GM approval and scheduling required before approval.",
    featured: true,
    seasonExclusive: true,
    almostGoneThreshold: 1,
  },
  {
    id: "reward-projection-tour",
    chapterId: chapter.id,
    name: "Projection Booth Tour",
    description: "A behind-the-scenes look at presentation, projection, and the magic upstairs.",
    milesCost: 1500,
    inventoryCount: 4,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Experience",
    collection: "Experience Rewards",
    tier: "Tier 3",
    enabled: true,
    sortOrder: 100,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "Schedule with GM or projection lead.",
    collector: true,
    almostGoneThreshold: 1,
  },
  {
    id: "reward-reserved-parking",
    chapterId: chapter.id,
    name: "Reserved Parking",
    description: "A close spot for a selected shift week.",
    milesCost: 1200,
    inventoryCount: 3,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Experience",
    collection: "Experience Rewards",
    tier: "Tier 3",
    enabled: true,
    sortOrder: 110,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "Admin assigns date range and communicates to leadership.",
    almostGoneThreshold: 1,
  },
  {
    id: "reward-collector-poster",
    chapterId: chapter.id,
    name: "Collector Poster",
    description: "Season One display piece inspired by premium cinema presentation.",
    milesCost: 850,
    inventoryCount: 6,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Gear",
    collection: "Collector's Vault",
    tier: "Tier 2",
    enabled: true,
    sortOrder: 120,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "Fulfill from collector vault inventory.",
    collector: true,
    seasonExclusive: true,
    almostGoneThreshold: 2,
  },
  {
    id: "reward-studio-merch",
    chapterId: chapter.id,
    name: "Studio Merchandise Drop",
    description: "A surprise movie merch item from the collector shelf.",
    milesCost: 1000,
    inventoryCount: 0,
    imageUrl: "/brand/celebration-c-frame.png",
    category: "Gear",
    collection: "Coming Soon",
    tier: "Tier 3",
    enabled: true,
    sortOrder: 130,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "Enable once inventory is received.",
    comingSoon: true,
    collector: true,
  },
];

export const redemptions: Redemption[] = [
  {
    id: "red-1",
    employeeId: "emp-alex",
    rewardId: "reward-movie-ticket",
    status: "Requested",
    requestedAt: "2026-07-24T14:15:00",
  },
  {
    id: "red-2",
    employeeId: "emp-nora",
    rewardId: "reward-c-cash-5",
    status: "Requested",
    requestedAt: "2026-07-24T12:40:00",
  },
  {
    id: "red-3",
    employeeId: "emp-maya",
    rewardId: "reward-c-cash-5",
    status: "Approved",
    requestedAt: "2026-07-23T16:20:00",
  },
];

export const experienceEvents: ExperienceEvent[] = [
  {
    id: "event-todays-focus-lobby-readiness",
    type: "Today's Focus",
    title: "Lobby readiness before the rush",
    description:
      "Recognize warm greetings, clear queues, clean sightlines, and confident guest answers before peak showtimes.",
    startAt: "2026-07-24T10:00:00",
    endAt: "2026-07-24T23:59:59",
    xpModifier: 1,
    eligibleRecognitionTypeIds: [
      "lobby_excellence",
      "floor_guest_welcome_run",
      "guest_compliment",
    ],
    departmentIds: ["floor", "guest_services", "box_office"],
    tvAnnouncement: "Today's Focus: Lobby readiness before the rush.",
    banner: "Make the first five minutes feel effortless.",
    enabled: true,
    sortOrder: 10,
  },
  {
    id: "event-community-challenge-imax",
    type: "Community Challenge",
    title: "IMAX 15/70 presentation push",
    description:
      "A community XP challenge for guest flow, auditorium resets, signage accuracy, and presentation details around premium shows.",
    startAt: "2026-07-25T00:00:00",
    endAt: "2026-07-27T23:59:59",
    xpModifier: 1.25,
    eligibleRecognitionTypeIds: [
      "theater_excellence",
      "digital_signage_excellence",
      "imax_queue_excellence",
      "auditorium_reset_detail",
    ],
    departmentIds: ["floor", "guest_services", "facilities"],
    tvAnnouncement: "Community Challenge: protect the premium IMAX experience.",
    banner: "Premium presentation earns bonus momentum.",
    enabled: true,
    sortOrder: 20,
  },
  {
    id: "event-surprise-drop-rewards",
    type: "Surprise Drop",
    title: "Collector reward drop",
    description:
      "Feature collector and season-exclusive rewards on the TV loop to drive attention during the weekend.",
    startAt: "2026-07-26T14:00:00",
    endAt: "2026-07-26T20:00:00",
    xpModifier: 1,
    eligibleRecognitionTypeIds: [],
    departmentIds: ["guest_services", "concessions", "kitchen", "floor", "box_office", "facilities"],
    tvAnnouncement: "Surprise Drop: check Rewards for collector items.",
    banner: "Limited rewards are live while inventory lasts.",
    enabled: true,
    sortOrder: 30,
  },
  {
    id: "event-season-finale",
    type: "Season Finale Event",
    title: "The Odyssey finale weekend",
    description:
      "A finale event for the last push toward Community XP, recognition coverage, and reward fulfillment.",
    startAt: "2026-08-10T00:00:00",
    endAt: "2026-08-12T23:59:59",
    xpModifier: 1.5,
    eligibleRecognitionTypeIds: [],
    departmentIds: ["guest_services", "concessions", "kitchen", "floor", "box_office", "facilities"],
    tvAnnouncement: "Season Finale: every Experience Moment counts.",
    banner: "Finish strong. Recognize the Moments that mattered.",
    enabled: false,
    sortOrder: 40,
  },
];

export const experienceDisplaySlides: ExperienceDisplaySlide[] = [
  {
    id: "display-community-xp",
    type: "Community XP",
    label: "Community XP",
    headline: "15,700 XP Starts With Daily Moments",
    supportingText: "Show progress toward the season goal without making recognition feel like a race.",
    durationSeconds: 7,
    showOnTv: true,
    lifecycle: "published",
    enabled: true,
    sortOrder: 10,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "display-todays-focus",
    type: "Today's Focus",
    label: "Today's Focus",
    headline: "Lobby Readiness Before The Rush",
    supportingText: "Help leaders keep recognition connected to the shift’s most important behavior.",
    durationSeconds: 7,
    showOnTv: true,
    lifecycle: "published",
    enabled: true,
    sortOrder: 20,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "display-recognition-spotlight",
    type: "Recognition Spotlight",
    label: "Recognition Spotlight",
    headline: "Moments That Mattered",
    supportingText: "Celebrate specific stories from the team, not just totals.",
    durationSeconds: 8,
    showOnTv: true,
    lifecycle: "published",
    enabled: true,
    sortOrder: 30,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "display-reward-spotlight",
    type: "Reward Spotlight",
    label: "Reward Spotlight",
    headline: "Rewards Worth Earning",
    supportingText: "Rotate several curated rewards so employees can see what is available.",
    durationSeconds: 8,
    showOnTv: true,
    lifecycle: "published",
    enabled: true,
    sortOrder: 40,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "display-experience-score",
    type: "Experience Score",
    label: "Experience Score",
    headline: "Culture Health At A Glance",
    supportingText: "A configurable composite of recognition coverage, presentation, and rewards health.",
    durationSeconds: 7,
    showOnTv: false,
    lifecycle: "draft",
    enabled: true,
    sortOrder: 50,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
];

export const scoringMetrics: ScoringMetric[] = [
  {
    id: "experience_score",
    label: "Experience Score",
    description: "Overall culture health across recognition, rewards, presentation, and season progress.",
    weight: 35,
    target: 90,
    currentValue: 86,
    lifecycle: "published",
    enabled: true,
    sortOrder: 10,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "leadership_health",
    label: "Leadership Health",
    description: "Measures leader follow-through, coaching rhythm, coverage, and handoff quality.",
    weight: 25,
    target: 85,
    currentValue: 83,
    lifecycle: "published",
    enabled: true,
    sortOrder: 20,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "presentation_score",
    label: "Presentation Score",
    description: "Measures excellence checks and building presentation readiness.",
    weight: 20,
    target: 92,
    currentValue: 91,
    lifecycle: "published",
    enabled: true,
    sortOrder: 30,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "recognition_coverage",
    label: "Recognition Coverage",
    description: "Measures whether recognition is reaching the full team, not only frequent standouts.",
    weight: 20,
    target: 88,
    currentValue: 83,
    lifecycle: "published",
    enabled: true,
    sortOrder: 40,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
];

export const launchReadinessItems: LaunchReadinessItem[] = [
  {
    id: "launch-season-configured",
    label: "Season configured",
    owner: "Experience Designer",
    status: "ready",
    dueDate: "2026-07-09",
    notes: "Season One: The Odyssey dates, goal, message, and skin are ready.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 10,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "launch-recognition-published",
    label: "Recognition published",
    owner: "Admin/GM",
    status: "ready",
    dueDate: "2026-07-09",
    notes: "Recognition and Experience Card task libraries are active.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 20,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "launch-rewards-published",
    label: "Rewards published",
    owner: "Admin/GM",
    status: "ready",
    dueDate: "2026-07-09",
    notes: "Rewards are grouped into curated collections and inventory thresholds are set.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 30,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "launch-events-scheduled",
    label: "Events scheduled",
    owner: "Experience Designer",
    status: "in_progress",
    dueDate: "2026-07-12",
    notes: "Opening focus is ready; finale and surprise drops need final approval.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 40,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "launch-cards-generated",
    label: "Experience Cards generated",
    owner: "Leader",
    status: "in_progress",
    dueDate: "2026-07-15",
    notes: "Print runs are available by employee and scheduled work area.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 50,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "launch-tv-configured",
    label: "TV configured",
    owner: "Experience Designer",
    status: "ready",
    dueDate: "2026-07-09",
    notes: "Slides, durations, and visibility are editable in Displays Studio.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 60,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "launch-employees-imported",
    label: "Employees imported",
    owner: "Admin/GM",
    status: "in_progress",
    dueDate: "2026-07-15",
    notes: "CSV/Excel import is available; final employee list still needs to be loaded.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 70,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "launch-auth-configured",
    label: "Authentication configured",
    owner: "Experience Designer",
    status: "in_progress",
    dueDate: "2026-07-15",
    notes: "Supabase Auth form is built; production users must be created in Supabase.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 80,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "launch-supabase-connected",
    label: "Supabase connected",
    owner: "Experience Designer",
    status: "in_progress",
    dueDate: "2026-07-15",
    notes: "Schema covers platform objects; environment variables control live persistence.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 90,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
];

export const experienceAchievements: ExperienceAchievement[] = [
  {
    id: "badge-first-moment",
    audience: "employee",
    title: "First Moment",
    description: "Earned when an employee receives their first Experience Moment.",
    collection: "Season Badges",
    hidden: false,
    badgeImageUrl: "/brand/celebration-c-frame.png",
    criteria: "First published Experience Moment in the active season.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 10,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "badge-premium-presentation",
    audience: "employee",
    title: "Premium Presentation",
    description: "Recognizes repeated presentation and detail moments.",
    collection: "Season Badges",
    hidden: false,
    badgeImageUrl: "/brand/celebration-c-frame.png",
    criteria: "Three presentation-related Experience Moments.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 20,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "badge-secret-recovery",
    audience: "employee",
    title: "Guest Recovery Signal",
    description: "Hidden badge for an exceptional guest recovery story.",
    collection: "Hidden Achievements",
    hidden: true,
    badgeImageUrl: "/brand/celebration-c-frame.png",
    criteria: "Leader marks an Experience Moment as hidden-achievement eligible.",
    lifecycle: "draft",
    enabled: true,
    sortOrder: 30,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "lead-achievement-coverage-builder",
    audience: "leader",
    title: "Coverage Builder",
    description: "Leader kept recognition coverage visible across departments for a full week.",
    collection: "Leadership Achievements",
    hidden: false,
    badgeImageUrl: "/brand/celebration-c-frame.png",
    criteria: "Recognition coverage reaches the weekly target.",
    lifecycle: "published",
    enabled: true,
    sortOrder: 40,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
];

export const leadershipPointRules: LeadershipPointRule[] = [
  {
    id: "lp-capture-specific-moment",
    name: "Capture specific Experience Moment",
    description: "Leader captures a clear, behavior-based story for an employee.",
    lpValue: 5,
    category: "Coaching",
    requiresNote: true,
    lifecycle: "published",
    enabled: true,
    sortOrder: 10,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "lp-close-coverage-gap",
    name: "Close recognition coverage gap",
    description: "Leader recognizes an employee who was awaiting recognition.",
    lpValue: 10,
    category: "Coverage",
    requiresNote: true,
    lifecycle: "published",
    enabled: true,
    sortOrder: 20,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
  {
    id: "lp-clean-shift-handoff",
    name: "Clean shift handoff",
    description: "Leader records a concise operational handoff that protects follow-through.",
    lpValue: 8,
    category: "Communication",
    requiresNote: true,
    lifecycle: "published",
    enabled: true,
    sortOrder: 30,
    seasonId: chapter.id,
    createdAt: nowSeed,
    updatedAt: nowSeed,
  },
];

export const studioModules: StudioModule[] = [
  {
    id: "season-planner",
    name: "Seasons",
    href: "/admin/season-planner",
    description: "Create, duplicate, preview, publish, and archive seasons.",
    status: "configured",
  },
  {
    id: "recognition",
    name: "Recognition",
    href: "/admin/recognition-library",
    description: "Manage Experience Moments, card tasks, excellence checks, XP, prompts, and areas.",
    status: "configured",
  },
  {
    id: "rewards",
    name: "Rewards",
    href: "/admin/rewards",
    description: "Curate reward collections, inventory, tiers, costs, and fulfillment notes.",
    status: "configured",
  },
  {
    id: "events",
    name: "Events",
    href: "/admin/events",
    description: "Schedule Today's Focus, bonus XP, surprise drops, and season events.",
    status: "configured",
  },
  {
    id: "standards",
    name: "Standards",
    href: "/admin/standards",
    description: "Edit the culture standards leaders recognize against.",
    status: "configured",
  },
  {
    id: "leadership",
    name: "Leadership",
    href: "/admin/leadership",
    description: "Configure Leadership Health, LP rules, leadership rewards, and coaching signals.",
    status: "configured",
  },
  {
    id: "achievements",
    name: "Achievements",
    href: "/admin/achievements",
    description: "Configure employee and leader badges, hidden achievements, and collections.",
    status: "configured",
  },
  {
    id: "displays",
    name: "Displays",
    href: "/admin/displays",
    description: "Control TV slides, visibility, timing, order, and display copy.",
    status: "configured",
  },
  {
    id: "scoring",
    name: "Scoring",
    href: "/admin/scoring",
    description: "Adjust Experience Score, Leadership Health, presentation, and coverage weights.",
    status: "configured",
  },
  {
    id: "launch-readiness",
    name: "Launch Readiness",
    href: "/admin/launch-readiness",
    description: "Track operational readiness before a season goes live.",
    status: "configured",
  },
];

export const employeeNav: NavItem[] = [
  { label: "Today", href: "/home", icon: Home },
  { label: "My Experience", href: "/my-journey", icon: Route },
  { label: "Rewards", href: "/rewards", icon: Gift },
  { label: "Profile", href: "/profile", icon: User },
];

export const managerNav: NavItem[] = [
  { label: "Capture Moment", href: "/manager/recognize", icon: HandHeart },
  { label: "Experience Card Entry", href: "/manager/passport", icon: ClipboardCheck },
  { label: "Print Daily Experience Cards", href: "/manager/cards", icon: BookOpen },
  { label: "Employee Lookup", href: "/manager/employees", icon: Search },
  { label: "Reward Approvals", href: "/manager/pending-rewards", icon: Gift },
];

export const adminNav: NavItem[] = [
  { label: "Recognition Builder", href: "/admin/recognition-library", icon: Library },
  { label: "Rewards Builder", href: "/admin/rewards", icon: Package },
  { label: "Employees", href: "/admin/employees", icon: Users },
  { label: "Settings", href: "/admin/settings", icon: Settings },
];

export const utilityNav: NavItem[] = [
  { label: "TV Display", href: "/tv", icon: MonitorPlay },
];

export const menuConfigurations: MenuConfiguration[] = [
  ...employeeNav.map((item, index) => ({
    id: `employee-${index}`,
    area: "Employee" as const,
    label: item.label,
    href: item.href,
    purpose: "Employee Experience navigation",
    enabled: true,
    reusable: true,
  })),
  ...managerNav.map((item, index) => ({
    id: `manager-${index}`,
    area: "Manager" as const,
    label: item.label,
    href: item.href,
    purpose: "Manager Lite navigation",
    enabled: true,
    reusable: true,
  })),
  ...adminNav.map((item, index) => ({
    id: `admin-${index}`,
    area: "Admin/GM" as const,
    label: item.label,
    href: item.href,
    purpose: "Experience Builder navigation",
    enabled: true,
    reusable: true,
  })),
  ...utilityNav.map((item, index) => ({
    id: `utility-${index}`,
    area: "Utility" as const,
    label: item.label,
    href: item.href,
    purpose: "Shared access and display modes",
    enabled: true,
    reusable: true,
  })),
];

export const roleLabels: Record<Role, string> = {
  employee: "Employee Experience",
  manager: "Manager",
  admin: "Experience Builder",
};

export const categoryIcons: Record<RecognitionCategory, typeof BadgeCheck> = {
  "Excellence Check": BadgeCheck,
  "Guest Experience": Sparkles,
  Teamwork: Users,
  Reliability: Gauge,
  Details: Film,
  "Manager Award": Award,
};

export function getEmployee(id: string) {
  return employees.find((employee) => employee.id === id);
}

export function getEmployeeByPassport(passportId: string) {
  return employees.find(
    (employee) => employee.passportId.toLowerCase() === passportId.toLowerCase(),
  );
}

export function getDepartment(id: DepartmentId) {
  return departments.find((department) => department.id === id);
}

export function getRecognitionType(id: string) {
  return recognitionTypes.find((type) => type.id === id);
}

export function getAction(key: string) {
  return getRecognitionType(key);
}

export function getStandard(id: string) {
  return recognitionStandards.find((standard) => standard.id === id);
}

export function getReward(id: string) {
  return rewards.find((reward) => reward.id === id);
}

export function getBatch(id?: string) {
  if (!id) {
    return undefined;
  }

  return recognitionBatches.find((batch) => batch.id === id);
}

export function getManagerRecognitions() {
  return recognitions
    .map((recognition) => ({
      ...recognition,
      employee: getEmployee(recognition.employeeId),
      manager: getEmployee(recognition.managerId),
      action: getRecognitionType(recognition.recognitionTypeId),
      standard: getStandard(recognition.standardId),
      batch: getBatch(recognition.batchId),
    }))
    .filter((recognition) => recognition.employee && recognition.action && recognition.standard);
}

export const communityMiles = departments.reduce(
  (total, department) => total + department.progressMiles,
  0,
);

export const todayMiles = recognitions
  .filter((recognition) => recognition.createdAt.startsWith("2026-07-24"))
  .reduce((total, recognition) => total + recognition.miles, 0);

export const employeesNotRecognizedThisWeek = employees.filter(
  (employee) => employee.role === "employee" && employee.weeklyMiles === 0,
);

export const recognitionOfTheDay =
  recognitions.find((recognition) => recognition.spotlight) ?? recognitions[0];

export const chapterStats = {
  communityMiles,
  todayMiles,
  remainingMiles: COMMUNITY_GOAL_MILES - communityMiles,
  averageDailyMiles: 538,
  activeEmployees: employees.filter((employee) => employee.role === "employee").length,
  pendingRedemptions: redemptions.filter((redemption) => redemption.status === "Requested").length,
  activeRecognitionTypes: recognitionTypes.filter((type) => type.enabled).length,
  activeRewards: rewards.filter((reward) => reward.enabled).length,
};

export const passportCsvPreview = employees
  .filter((employee) => employee.role === "employee")
  .map((employee) => ({
    name: employee.name,
    passportId: employee.passportId,
    department: getDepartment(employee.department)?.name ?? "",
    cardArea:
      journeyCardAreas.find((area) => area.id === employee.journeyCardAreaId)?.name ??
      "",
  }));

export const chapterSettings = [
  ["Season name", chapter.name],
  ["Season subtitle", chapter.subtitle],
  ["Start date", chapter.startDate],
  ["End date", chapter.endDate],
  ["Community XP goal", `${chapter.communityGoalMiles}`],
  ["Theme label", chapter.themeLabel],
  ["Active", chapter.active ? "Yes" : "No"],
  ["Season tagline", chapter.visualTagline],
  ["Theme note", chapter.themeNote],
];

export const launchReadinessChecklist = launchReadinessItems.map((item) => ({
  label: item.label,
  status: item.status.replace("_", " "),
}));

export const filmFacts = [
  "15/70 reference",
  "Projection-inspired motion",
  "Film grain and perforation accents",
  "Experience leaderboard available in app and TV display",
];

export const journalEvents = [
  {
    date: "Jul 24",
    title: "Experience Card verified",
    detail: "4 checked items became 40 XP after manager review.",
  },
  {
    date: "Jul 22",
    title: "Crew moment",
    detail: "Helped concessions clear a line before previews started.",
  },
  {
    date: "Jul 16",
    title: "Season opened",
    detail: "The Odyssey began with every Experience Moment counting toward 15,700 XP.",
  },
];

export const tvPanels = [
  "Odyssey Signal",
  "Community XP",
  "Today's Focus",
  "Experience Leaderboard",
  "15,700 / IMAX 1570",
  "Recognition Spotlight",
  "Recognition Wall",
  "Department Progress",
  "Reward Spotlight",
  "Countdown",
];

export const tvPanelSettings: TvPanelSetting[] = tvPanels.map((panel, index) => ({
  id: panel.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, ""),
  label: panel,
  enabled: true,
  sortOrder: index + 1,
  seconds: panel === "Recognition Wall" ? 9 : 7,
}));

export const iconNames = [
  "Award",
  "BadgeCheck",
  "CalendarDays",
  "ClipboardCheck",
  "Clapperboard",
  "Film",
  "Gauge",
  "Gift",
  "HandHeart",
  "Megaphone",
  "MonitorPlay",
  "Route",
  "Sparkles",
  "Store",
  "Users",
  "BookOpen",
];

export const adminQuickLinks = [
  { label: "Add Recognition Type", href: "/admin/recognition-library/new", icon: Library },
  { label: "Experience Cards", href: "/manager/cards", icon: BookOpen },
  { label: "Reward Inventory", href: "/admin/rewards", icon: Coins },
];
