import type { RecognitionType, Reward } from "@/lib/types";

const allCrewQuestAreas = [
  "concessions",
  "kitchen_oscars",
  "floor_lobby",
  "box_guest_services",
  "facilities_exterior",
];

export const ODYSSEY_RECOGNITION_TYPE_IDS = [
  "odyssey_crew_quest_card",
  "odyssey_guest_compliment",
  "odyssey_pick_up_shift",
  "odyssey_stay_late",
  "odyssey_perfect_attendance",
  "odyssey_weekend_warrior",
  "odyssey_above_beyond",
  "odyssey_prioritization_worksheet",
  "odyssey_team_photo",
] as const;

export const ODYSSEY_REWARD_IDS = [
  "odyssey-reward-c-cash-5",
  "odyssey-reward-t-shirt",
  "odyssey-reward-movie-ticket",
  "odyssey-reward-gift-card-10",
  "odyssey-reward-c-cash-10",
  "odyssey-reward-uniform-15",
  "odyssey-reward-meal-voucher",
  "odyssey-reward-gift-card-25",
  "odyssey-reward-c-cash-25",
  "odyssey-reward-lego-medium",
  "odyssey-reward-paycheck-25",
  "odyssey-reward-owala",
  "odyssey-reward-uniform-30",
  "odyssey-reward-gift-card-50",
  "odyssey-reward-lego-large",
  "odyssey-reward-paycheck-50",
] as const;

export function createOdysseyRecognitionTypes(chapterId: string): RecognitionType[] {
  return [
    {
      id: "odyssey_crew_quest_card",
      chapterId,
      name: "Complete a Crew Quest Card",
      description:
        "Turn in one verified Crew Quest card for the shift and area worked. This can be earned more than once during the four-week voyage.",
      category: "Manager Award",
      standardId: "detail_matters",
      milesValue: 25,
      icon: "ClipboardCheck",
      enabled: true,
      requiresManagerVerification: true,
      sortOrder: 1,
      type: "journey_card_task",
      creditScope: "employee",
      journeyCardEligible: true,
      journeyCardAreaIds: allCrewQuestAreas,
      status: "published",
      lifecycle: "published",
    },
    {
      id: "odyssey_guest_compliment",
      chapterId,
      name: "Guest Compliment",
      description: "A guest specifically complimented the crew member's service.",
      category: "Guest Experience",
      standardId: "guest_welcome",
      milesValue: 50,
      icon: "Sparkles",
      enabled: true,
      requiresManagerVerification: true,
      sortOrder: 2,
      type: "guest_experience",
      status: "published",
      lifecycle: "published",
    },
    {
      id: "odyssey_pick_up_shift",
      chapterId,
      name: "Pick Up an Available Shift",
      description: "Picked up an available shift when the crew needed support.",
      category: "Reliability",
      standardId: "shift_counts",
      milesValue: 20,
      icon: "CalendarDays",
      enabled: true,
      requiresManagerVerification: true,
      sortOrder: 3,
      type: "reliability",
      status: "published",
      lifecycle: "published",
    },
    {
      id: "odyssey_stay_late",
      chapterId,
      name: "Stay Late to Support the Team",
      description: "Stayed late at a manager's request to support the team.",
      category: "Reliability",
      standardId: "shift_counts",
      milesValue: 15,
      icon: "Gauge",
      enabled: true,
      requiresManagerVerification: true,
      sortOrder: 4,
      type: "reliability",
      status: "published",
      lifecycle: "published",
    },
    {
      id: "odyssey_perfect_attendance",
      chapterId,
      name: "Perfect Attendance for a Week",
      description: "Award once per week after the crew member completes a perfect attendance week.",
      category: "Reliability",
      standardId: "shift_counts",
      milesValue: 25,
      icon: "BadgeCheck",
      enabled: true,
      requiresManagerVerification: true,
      sortOrder: 5,
      type: "reliability",
      status: "published",
      lifecycle: "published",
    },
    {
      id: "odyssey_weekend_warrior",
      chapterId,
      name: "Weekend Warrior",
      description: "Worked Friday, Saturday, and Sunday. Award once per qualifying week.",
      category: "Reliability",
      standardId: "shift_counts",
      milesValue: 30,
      icon: "Award",
      enabled: true,
      requiresManagerVerification: true,
      sortOrder: 6,
      type: "reliability",
      status: "published",
      lifecycle: "published",
    },
    {
      id: "odyssey_above_beyond",
      chapterId,
      name: "Go Above & Beyond",
      description: "Manager-awarded recognition for uncommon ownership or support.",
      category: "Manager Award",
      standardId: "detail_matters",
      milesValue: 20,
      icon: "Award",
      enabled: true,
      requiresManagerVerification: true,
      sortOrder: 7,
      type: "detail",
      status: "published",
      lifecycle: "published",
    },
    {
      id: "odyssey_prioritization_worksheet",
      chapterId,
      name: "Complete the Prioritization Worksheet",
      description: "Completed and turned in the Odyssey prioritization worksheet.",
      category: "Details",
      standardId: "detail_matters",
      milesValue: 50,
      icon: "ClipboardCheck",
      enabled: true,
      requiresManagerVerification: true,
      sortOrder: 8,
      type: "detail",
      status: "published",
      lifecycle: "published",
    },
    {
      id: "odyssey_team_photo",
      chapterId,
      name: "Team Photo",
      description: "Shared an approved team photo in shirts or the OurPeople chat. Limit three per day.",
      category: "Teamwork",
      standardId: "crew_matters",
      milesValue: 5,
      icon: "Camera",
      enabled: true,
      requiresManagerVerification: true,
      sortOrder: 9,
      type: "teamwork",
      status: "published",
      lifecycle: "published",
    },
  ];
}

type OdysseyRewardSeed = Pick<
  Reward,
  "id" | "name" | "description" | "milesCost" | "category" | "collection" | "tier"
>;

const rewardSeeds: OdysseyRewardSeed[] = [
  { id: "odyssey-reward-c-cash-5", name: "$5 C Cash", description: "Celebration Cinema C Cash.", milesCost: 75, category: "Cinema", collection: "Everyday Rewards", tier: "Tier 1" },
  { id: "odyssey-reward-t-shirt", name: "Special Odyssey T-Shirt", description: "Season-exclusive Odyssey crew shirt, while supplies last.", milesCost: 125, category: "Gear", collection: "Season Exclusives", tier: "Tier 1" },
  { id: "odyssey-reward-movie-ticket", name: "Movie Ticket", description: "One movie ticket.", milesCost: 150, category: "Cinema", collection: "Everyday Rewards", tier: "Tier 1" },
  { id: "odyssey-reward-gift-card-10", name: "Your Choice Gift Card ($10)", description: "Choose from the available $10 gift cards.", milesCost: 150, category: "Experience", collection: "Everyday Rewards", tier: "Tier 1" },
  { id: "odyssey-reward-c-cash-10", name: "$10 C Cash", description: "Celebration Cinema C Cash.", milesCost: 150, category: "Cinema", collection: "Everyday Rewards", tier: "Tier 1" },
  { id: "odyssey-reward-uniform-15", name: "Free Uniform Item ($15 Value)", description: "Choose an eligible uniform item up to $15.", milesCost: 200, category: "Gear", collection: "Everyday Rewards", tier: "Tier 1" },
  { id: "odyssey-reward-meal-voucher", name: "Free Meal Voucher", description: "One eligible meal voucher.", milesCost: 200, category: "Food", collection: "Everyday Rewards", tier: "Tier 1" },
  { id: "odyssey-reward-gift-card-25", name: "Your Choice Gift Card ($25)", description: "Choose from the available $25 gift cards.", milesCost: 275, category: "Experience", collection: "Featured Rewards", tier: "Tier 2" },
  { id: "odyssey-reward-c-cash-25", name: "$25 C Cash", description: "Celebration Cinema C Cash.", milesCost: 275, category: "Cinema", collection: "Featured Rewards", tier: "Tier 2" },
  { id: "odyssey-reward-lego-medium", name: "Medium LEGO Set", description: "Choose from the available medium LEGO sets.", milesCost: 300, category: "Gear", collection: "Featured Rewards", tier: "Tier 2" },
  { id: "odyssey-reward-paycheck-25", name: "$25 Bonus on Paycheck", description: "A $25 payroll bonus, subject to normal payroll processing.", milesCost: 300, category: "Experience", collection: "Featured Rewards", tier: "Tier 2" },
  { id: "odyssey-reward-owala", name: "Owala Water Bottle", description: "An Owala water bottle, while supplies last.", milesCost: 325, category: "Gear", collection: "Featured Rewards", tier: "Tier 2" },
  { id: "odyssey-reward-uniform-30", name: "Free Uniform Item ($30 Value)", description: "Choose an eligible uniform item up to $30.", milesCost: 350, category: "Gear", collection: "Featured Rewards", tier: "Tier 2" },
  { id: "odyssey-reward-gift-card-50", name: "Your Choice Gift Card ($50)", description: "Choose from the available $50 gift cards.", milesCost: 450, category: "Experience", collection: "Featured Rewards", tier: "Tier 3" },
  { id: "odyssey-reward-lego-large", name: "Large LEGO Set", description: "Choose from the available large LEGO sets.", milesCost: 500, category: "Gear", collection: "Featured Rewards", tier: "Tier 3" },
  { id: "odyssey-reward-paycheck-50", name: "$50 Bonus on Paycheck", description: "A $50 payroll bonus, subject to normal payroll processing.", milesCost: 500, category: "Experience", collection: "Featured Rewards", tier: "Tier 3" },
];

export function createOdysseyRewards(chapterId: string): Reward[] {
  return rewardSeeds.map((reward, index) => ({
    ...reward,
    chapterId,
    inventoryCount: 0,
    imageUrl: "/brand/celebration-c-frame.png",
    enabled: true,
    sortOrder: index + 1,
    redemptionLimitPerEmployee: 1,
    fulfillmentNotes: "Set inventory and fulfillment details in Rewards before accepting redemptions.",
    featured: reward.collection === "Featured Rewards",
    seasonExclusive: reward.collection === "Season Exclusives",
    almostGoneThreshold: 2,
    status: "published",
    lifecycle: "published",
  }));
}
